#!/bin/sh

# Launch hotkey daemon sxhkd and reload the configuration.
pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor and workspaces.
bspc monitor -d 1 2 3

# Configuration.
bspc config split ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config click_to_focus none
bspc config border_width 8
bspc config window_gap 15

# Color.
bspc config normal_border_color "#dce1eb"
bspc config focused_border_color "#5e81ac"

# Reset rules.
bspc rule -r "*"
