name: main
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  CI_NIX_FLAKE: .#default
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache Nix
        uses: DeterminateSystems/flakehub-cache-action@main
      - name: Lint
        run: |
          nix develop ${{ env.CI_NIX_FLAKE }} --command \
            editorconfig-checker && echo "ok"
